pogom/app.py, pogom/models.py, runserver.py, templates/map.html
=> Scheduler Added

pogom/app.py, pogom/utils.py, runserver.py
=> update worker location + configurable stepsize and radius

pogom/app.py
=> [UPDATE] add image url to gymdetails

pogom/app.py
=> [UPDATE] add unhatched raids

pogom/models.py
=> [UPDATE] reduce deviceid size

pogom/app.py, pogom/utils.py, runserver.py
=> Changemaplocation

pogom/app.py, runserver.py
=> Webhooks re-added

pogom/app.py, pogom/utils.py
=> Teleport scan

pogom/app.py
=> [FIX] typo in pokestop webhook

pogom/app.py
=> [FIX] typo

config/config.ini.example, pogom/app.py, pogom/utils.py, templates/map.html, templates/statistics.html
=> Configure Mapname

pogom/app.py, pogom/models.py
=> bugfix + initial pokemon feed

pogom/app.py
=> bugfix feed

pogom/app.py
=> [UPDATE] parse lat and long in post data to float

pogom/app.py
=> [UPDATE] fixes bug in r91a

pogom/app.py, pogom/utils.py
=> Quests - Save Item quests & send coords to webhook

pogom/app.py, pogom/models.py
=> Protos working - IV enabled

pogom/app.py
=> Protos - updates

static/js/map.common.js, static/js/map.js
=> [UPDATE] updates to pokemon labels

static/js/map.js
=> [UPDATE] add raidstr back to gymlabel

pogom/app.py
=> [UPDATE] possible fix for iv's

pogom/app.py
=> [UPDATE] fix in webhook quests without raw protos

pogom/app.py, static/js/map.js
=> [UPDATE] map fix for encountered pokemon?

pogom/app.py
=> [UPDATE] error handling for not raw protos posts

pogom/models.py, static/js/map.js, static/sass/layout/_gym.scss, static/sass/layout/_pokestop-details.scss, static/sass/layout/_pokestop.scss
=> add gym and poke stop img.

static/js/map.js, static/sass/layout/_pokestop-details.scss, static/sass/layout/_pokestop.scss
=> display pokestop quest.

pogom/models.py, static/js/map.js, static/js/stats.js, static/sass/layout/_deviceworker.scss, static/sass/layout/_pokestop.scss, static/sass/layout/_stats.scss, static/sass/main.scss, templates/map.html
Deviceworker stats and markers.
=> Deviceworker stats and markers

static/js/map.js
=> Fix for raid start time not showing up on the gym label

pogom/app.py, pogom/utils.py
Apply optional jitter to the coordinates when using teleport_gpx endpoint
=> Add jitter to teleport_gpx endpoint

pogom/app.py
Apply optional jitter to the coordinates when using teleport_gym endpoint
=> Add jitter to teleport_gym endpoint

static/data/pokedex/moves.json
Added types and changed names to match the existing format. Added move 0 as an unknown move in case we cannot pull the moves of mons and gyms.
Get these out of the way for new moves to show on the map.
Tested on my server.
=> Updated Move List

pogom/app.py
=> Process FortDetailsResponse proto

pogom/app.py
=> little tweak for pr81

pogom/app.py, pogom/models.py, pogom/utils.py
=> [UPDATE] add expiration of quest info

pogom/userAuth.py
The invite to the discord was not being presented at the right time. I moved it so that after it fails to get any roles (meaning they are not part of the server yet) they will be directed to join the server.
I also changed the log level of people authenticating so you can see when someone fails any possibly assist them.
=> Update userAuth.py for Server Invite and Logging

pogom/utils.py, static/js/map.js
=> Tweaks to map for pokestop / quest filtering

.github/ISSUE_TEMPLATE.md
issue template had link to RocketMap discord and devkat voting
This has caused users to look for help there and not get advised
=> Remove discord invite from ISSUE_TEMPLATE.md

CODE_OF_CONDUCT.md, CONTRIBUTING.md, Dockerfile.dev, package.json, scalingo.json
Removed some references to old repo/discord/maintainers
Removed references to RocketMap/RocketMap from a couple main dir files, removed references to discord.gg/rocketmap and one of my emails.
We've gotten a few people coming in asking for support for this fork, so I removed some of the main offenders (aka, main directory files).
It should be noted there is a *ton* of references still remaining in the docs folder (and a few elsewhere) to the old readthedocs site (rocketmap.readthedocs.io) and potentially more repo/discord references, but RTD doesn't seem to be in use here so I've kind of disregarded it for now. It might be useful to simply remove the entire docs folder if not planning on using RTD, or to go and change all instances to the new link if using it. For the context of this PR, …
=> Remove repo/discord/maintainer references

pogom/app.py
=> Fix for weather alerts

Gruntfile.js, pogom/app.py, pogom/models.py, static/js/raids.js, static/sass/layout/_raids.scss, static/sass/raids.scss, templates/raids.html
Overview of all the raids in the area sorted bij ending time
=> Raid overview page

pogom/app.py
=> Update webhook for GET

pogom/app.py
=> Fix for gpx endpoints

pogom/dyn_img.py
Remember to clear out the old images from the 'generated' folder!
=> Fix for uncontested gyms and tweak layout for new icons

pogom/app.py
=> [UPDATE] only show active devices linked to current instance

pogom/app.py, pogom/models.py, pogom/utils.py
=> No overlap

static/js/raids.js, templates/raids.html
=> Added EX-Raid filter

static/js/quests.js, static/js/raids.js
=> Questpagesorted

pogom/models.py
After some time MySQL closes database connections.
=> Reconnct on closed database connections

pogom/geofence.py
=> Fix for geofence boundary calculation issue

pogom/app.py
Device username fix broke, owner username save, so it did it everytime.
Fixed missed functions in scan_loc
bugfixes
My environment only
=> fixes after username update and unifiedEndpoint

pogom/app.py
Default if not used is None not ''
=> Fix if no google analytics is to be used to track events

pogom/app.py
Fixes so mapcontrolled walk_pokestop knows it is mapcontrolled
code is redundant and creates an error after unifiedEndpoints was implemented
=> Removed code stopping function do understand it is mapcontrolled

static/js/app.js, static/js/find.js, static/sass/layout/_find.scss, templates/map.html
Shows quests if known in Stops/gyms
Search for quests in quest part of findPane
=> Displays quest for known pokestops in finePane

static/js/find.js
fixed broken icons
update quest icons to correspond with rewards
=> findpane icon update

pogom/models.py
=> Fix to allow deletings from PokestopMember during db_cleanup
